### ISSUE TITLE
Suggestion: Creating subtitles/caption

### ISSUE THREAD

**Issue by mikewink** [sylvainjule/kirby-subtitler#2]
The moment I saw the short GIF I thought, wow an editor to create video captions/subtitles on the fly inside of the Kirby Panel. 

As far as I can see it should be possible to create the needed WebVTT file from the generated content. What it needs is a snippet that formates the structure according to the spec. and then returns it to the track child element of the video element. 🤔 

A great resource with more information over on [MDN](https://developer.mozilla.org/en-US/Apps/Fundamentals/Audio_and_video_delivery/Adding_captions_and_subtitles_to_HTML5_video)

**Comment by sylvainjule** [comment]
I'm ashamed of this long delay to reply, apologies! I'm looking into this for the updated plugin for Kirby v3. :)

**Comment by sylvainjule** [comment]
Ready for v3 ✅
